default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: delper_new

test:
  <<: *default
  database: delper_new_development

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  
